//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMofaUniversity.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tblCourse
    {
        public int CID { get; set; }
        [Required(ErrorMessage = "Please enter course code")]
        [Display(Name ="Course Code :" )]
        public string Course_Code { get; set; }
        [Required(ErrorMessage = "Please enter course Title")]
        [Display(Name = "Course Title :")]
        public string Course_Title { get; set; }
        [Required(ErrorMessage = "Please enter course mejor or non-mejor")]
        [Display(Name = "Major/NonMajor :")]
        public string MajorNonMajor { get; set; }
        [Required(ErrorMessage = "Please enter course mark")]
        [Display(Name = "Course Marks :")]
        public string Marks { get; set; }
        [Required(ErrorMessage = "Please enter course credit")]
        [Display(Name = "Course Credit :")]
        public Nullable<double> Credit { get; set; }
        [Required(ErrorMessage = "Please enter course Semester")]
        [Display(Name = "Course Semester :")]
        public Nullable<int> SID { get; set; }
    }
}
