//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMofaUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMidResult
    {
        public int MidResultID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<double> FirstMidMark { get; set; }
        public Nullable<double> SecondtMidMark { get; set; }
    }
}
