//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web;

namespace DMofaUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResource
    {
        public int ResourceID { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string FilePath { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public string FileTitle { get; set; }
        public string FileAuthor { get; set; }
    }
}
