//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMofaUniversity.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tblRole
    {
        public int RoleID { get; set; }
        [Required(ErrorMessage = "please enter the role name")]
        [Display(Name = "Role Name :")]
        public string Role_Name { get; set; }
        [Required(ErrorMessage = "please create or enter your pridefined  the role Code")]
        [Display(Name = "Roll Code :")]
        public string Role_Code { get; set; }
    }
}
