//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web;

namespace DMofaUniversity.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tblStudent
    {
        public int StudentID { get; set; }
        public string Roll { get; set; }
        [Required(ErrorMessage = "please enter the Name")]
        [Display(Name = "Name :")]
        public string Name { get; set; }
      
        [Display(Name = "Image :")]
        public string StudentImagePath { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        [Required(ErrorMessage = "please enter the department")]
        [Display(Name = "Department :")]
        public string Deparment { get; set; }
        [Required(ErrorMessage = "please select semester")]
        [Display(Name = "Semester :")]
        public Nullable<int> SemisterID { get; set; }
        [Required(ErrorMessage = "please select the batch")]
        [Display(Name = "Semester :")]
        public Nullable<int> BatchID { get; set; }
        [Required(ErrorMessage = "please select the Sesson")]
        [Display(Name = "Sesson :")]
        public Nullable<int> SessonID { get; set; }
        [Required(ErrorMessage = "please enter father name")]
        [Display(Name = "Father Name :")]
        public string F_Name { get; set; }
        [Required(ErrorMessage = "please enter Mother name")]
        [Display(Name = "Mother Name :")]
        public string M_Name { get; set; }      
        [Display(Name = "BirthDate :")]
        public Nullable<System.DateTime> BirthDate { get; set; }
        [Required(ErrorMessage = "please enter national ID")]
        [Display(Name = "National ID :")]
        public string NationalID { get; set; }
        [Required(ErrorMessage = "please enter Age")]
        [Display(Name = "Age :")]
        public Nullable<int> Age { get; set; }
        [Required(ErrorMessage = "please enter Religion")]
        [Display(Name = "Religion :")]
        public string Religion { get; set; }
        [Required(ErrorMessage = "please enter caste")]
        [Display(Name = "Caste :")]
        public string Caste { get; set; }
        [Required(ErrorMessage = "please enter Nationality")]
        [Display(Name = "Nationality :")]
        public string Nationality { get; set; }
        [Required(ErrorMessage = "please enter Mobile")]
        [Display(Name = "Mobile :")]
        public string Mobile { get; set; }
        [Required(ErrorMessage = "please enter SSC passed year")]
        [Display(Name = "SSC Passed year :")]
        public string Ssc_passed_Yeae { get; set; }
        [Required(ErrorMessage = "please enter SSC Roll")]
        [Display(Name = "SSC Roll :")]
        public string Ssc_Roll { get; set; }
        [Required(ErrorMessage = "please enter SSC Result")]
        [Display(Name = "SSC Result :")]
        public string Ssc_Result { get; set; }
        [Required(ErrorMessage = "please enter SSC Board")]
        [Display(Name = "SSC Board :")]
        public string Ssc_Board { get; set; }
        [Required(ErrorMessage = "please enter HSC passed year")]
        [Display(Name = "HSC Passed year :")]
        public string Hsc_passed_Yeae { get; set; }
        [Required(ErrorMessage = "please enter HSC Roll")]
        [Display(Name = "HSC Roll :")]
        public string Hsc_Roll { get; set; }
        [Required(ErrorMessage = "please enter HSC Result")]
        [Display(Name = "HSC Result :")]
        public string Hsc_Result { get; set; }
        [Required(ErrorMessage = "please enter SSC Board")]
        [Display(Name = "SSC Board :")]
        public string Hsc_Board { get; set; }
        [Required(ErrorMessage = "please enter Email")]
        [Display(Name = "Email :")]
        public string Email { get; set; }
        [Required(ErrorMessage = "please enter Division")]
        [Display(Name = "Division :")]
        public string Division { get; set; }
        [Required(ErrorMessage = "please enter District")]
        [Display(Name = "District :")]
        public string Distric { get; set; }
        [Required(ErrorMessage = "please enter Thana")]
        [Display(Name = "Thana :")]
        public string Thana { get; set; }
        [Required(ErrorMessage = "please enter Post Office")]
        [Display(Name = "Post Office :")]
        public string Post_Office { get; set; }
        [Required(ErrorMessage = "please enter Post Code")]
        [Display(Name = "Post Code :")]
        public string Post_Code { get; set; }
        [Required(ErrorMessage = "please enter Present address")]
        [Display(Name = "Present address :")]
        public string Present_Address { get; set; }
        [Required(ErrorMessage = "please enter Guardian Name")]
        [Display(Name = "Guardian Name :")]
        public string Guardian_Name { get; set; }
        [Required(ErrorMessage = "please enter Guardian Mobile")]
        [Display(Name = "Guardian Mobile :")]
        public string Guardian_mobile { get; set; }
        [Required(ErrorMessage = "please enter Guardian Email")]
        [Display(Name = "Guardian Email :")]
        public string Guardian_Email { get; set; }
    }
}
