//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMofaUniversity.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tblSemester
    {
        public int SID { get; set; }
        [Required(ErrorMessage = "Please enter the Semester")]
        [Display(Name = "Semester :")]
        public string Semester { get; set; }
    }
}
