//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web;

namespace DMofaUniversity.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tblTeacher
    {
        public int TeacherID { get; set; }
        [Required(ErrorMessage = "Please enter your name")]
        [Display(Name = "Name :")]
        public string Name { get; set; }
        [Display(Name = "Teacher's Image :")]
        public string TeacherImagePath { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        [Required(ErrorMessage = "Please enter your department")]
        [Display(Name = "Department :")]
        public string Deparment { get; set; }
        [Required(ErrorMessage = "Please enter your Father Name")]
        [Display(Name = "Father Name :")]
        public string F_Name { get; set; }
        [Required(ErrorMessage = "Please enter your Mother Name")]
        [Display(Name = "Mother Name :")]
        public string M_Name { get; set; }
        [Required(ErrorMessage = "Please enter your Birth date")]
        [Display(Name = "Birth Date :")]
        public DateTime BirthDate { get; set; }
        [Required(ErrorMessage = "Please enter your National ID")]
        [Display(Name = "National ID :")]
        public string NationalID { get; set; }
        [Required(ErrorMessage = "Please enter your Age")]
        [Display(Name = "Age :")]
        public int Age { get; set; }
        [Required(ErrorMessage = "Please enter your Religion")]
        [Display(Name = "Religion :")]
        public string Religion { get; set; }
        [Required(ErrorMessage = "Please enter your Caste")]
        [Display(Name = "Caste :")]
        public string Caste { get; set; }
        [Required(ErrorMessage = "Please enter your Nationality")]
        [Display(Name = "Nationality :")]
        public string Nationality { get; set; }
        [Required(ErrorMessage = "Please enter your Mobile")]
        [Display(Name = "Mobile :")]
        public string Mobile { get; set; }
        [Required(ErrorMessage = "Please enter your BSc Result")]
        [Display(Name = "BSc Result :")]
        public string BSc_Result { get; set; }
        [Required(ErrorMessage = "Please enter your BSc Univarsity")]
        [Display(Name = "BSc Univarsity :")]
        public string BSc_Univarsity { get; set; }
        [Required(ErrorMessage = "Please enter your MSc Result")]
        [Display(Name = "MSc Result :")]
        public string MSc_Result { get; set; }
        [Required(ErrorMessage = "Please enter your MSc Univarsity")]
        [Display(Name = "MSc Univarsity :")]
        public string MSc_Univarsity { get; set; }
        [Required(ErrorMessage = "Please enter your Email")]
        [Display(Name = "Email :")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter your Division")]
        [Display(Name = "Division :")]
        public string Division { get; set; }
        [Required(ErrorMessage = "Please enter your District")]
        [Display(Name = "District :")]
        public string Distric { get; set; }
        [Required(ErrorMessage = "Please enter your Thana")]
        [Display(Name = "Thana :")]
        public string Thana { get; set; }
        [Required(ErrorMessage = "Please enter your Post Office")]
        [Display(Name = "Post Office :")]
        public string Post_Office { get; set; }
        [Required(ErrorMessage = "Please enter your Post Code")]
        [Display(Name = "Post Code :")]
        public string Post_Code { get; set; }
        [Required(ErrorMessage = "Please enter your present address")]
        [Display(Name = "Present Address :")]
        public string Present_Address { get; set; }
    }
}
