//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMofaUniversity.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tblUser
    {
        public int UserID { get; set; }
        [Required(ErrorMessage = "Please enter your usser name")]
        [Display(Name = "User Name :")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Please enter your email")]
        [Display(Name = "Email :")]
        [RegularExpression("^[a-zA-Z0-9_.-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+$", ErrorMessage = "Must be a valid email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter your password")]
        [Display(Name = "Password :")]
        [StringLength(255, ErrorMessage = "Must be between 5 and 255 characters", MinimumLength = 5)]
        [DataType(DataType.Password)]
        public string User_Password { get; set; }
        [Required(ErrorMessage = "Confirmation Password is required.")]
        [Compare("User_Password", ErrorMessage = "Password and Confirmation Password must match.")]
        [Display(Name = "Confirm Password :")]
        [StringLength(255, ErrorMessage = "Must be between 5 and 255 characters", MinimumLength = 5)]
        [DataType(DataType.Password)]
        public string User_CPassword { get; set; }
        public string User_RoleId { get; set; }
        [Required(ErrorMessage = "Please enter your Role Code")]
        [Display(Name = "Code :")]
        [DataType(DataType.Password)]
        public string Code { get; set; }
    }
}
